### ISSUE TITLE
setup CI

### ISSUE THREAD

**Issue by alphaolomi** [alphaolomi/laravel-shoket#3]

**Comment by RishiKumarRay** [comment]
@alphaolomi i want to work on this but i don't see any files

**Comment by alphaolomi** [comment]
Hey @RishiKumarRay thanks for finding interest in this project, its till very early,

Am looking forward in using the https://github.com/spatie/package-skeleton-php as the starter code and move on from there with other issues to 

If you can setup the starter code it will be very helpful

the project will use https://docs.guzzlephp.org/en/stable/ HTTP Client to handle communications with Shoket servers

Currently Shoket supports Payments Collection and Payments Verification this will be a great start

For more info regarding Shoket visit [their page](https://shoket.co/)
